version: '3.2'

services:
  web:
    image: anamba/awdwr    # use this to download and run the already-compiled image from Docker Hub
    # build: .             # use this one if you want to play with Docker on your own (edit Dockerfile, `docker-compose build`)
    ports:
      - '3000'
    # links:
    #   - db
    environment:
      PASSENGER_APP_ENV: development
      
  # db:
  #   image: mariadb:10.2.11
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
